### ISSUE TITLE
Create function to 'input' information about an existing prediction model

### ISSUE THREAD

**Issue by GlenMartin31** [GlenMartin31/predRupdate#1]
# Overview
The first function needed is one that takes a vector of coefficients (e.g. as published by the existing model) and a new dataset (the local data on which one wishes to apply the previous/existing prediction model) to calculate the predicted risks

## Intended Outcome
Input the relevant information of an existing prediction model (e.g. coefficients), and the ‘new data’, in such a way that the two are compatible with each other, and use these inputs to output each individuals (in the new data) predicted risk and linear predictor.

# Tasks
- [x] Create function outline
- [x] Create tests within function that ensures inputs are compatible
- [x] Add matrix multiplication of coefficients and new data to calculate the linear predictor; convert the LP into predicted risk and output both of these quantities
