### ISSUE TITLE
Advance the pm_input_info function

### ISSUE THREAD

**Issue by GlenMartin31** [GlenMartin31/predRupdate#3]
# Overview
The current version of the pm_input_info() function can take a (named) vector of coefficients, a functional form of the existing prediction model, and a new dataset, and standardise the inputs into a common "blueprint" for further evaluation in other functions in the package. We now need to advance this key function in several ways.

## Intended Outcome
A full version of the pm_input_info() function that can handle both logistic regression and time-to-event existing prediction models. It also needs to correctly handle any non-linear/spline terms within the existing model (or variable transformations), such that the function ensures compatibility between all the inputs, in the most user friendly way possible. 

# Tasks
- [x] Update to deal with factor variables correctly - i.e. create dummy variables to match naming given in existing coefficients
- [x] Update to allow for variable transformations/ splines within the model, while the function checks compatibility
- [x] Update to deal with variable interactions
- [x] Update to allow for time-to-event based prediction models
- [x] Add rigorous error-checking statements at the start of the function to ensure all inputs are entered as required (while also ensuring that the format of the inputs is the most user-friendly as possible) 
- [x] Add testthat - check error messages and some simple outputs
- [ ] change the options for input "model_type" to be more informative for the time-to-event based prediction models (i.e. current option of "survival" is too generic)
- [ ] Within the input "baselinehazard", allow an option for a parametric distribution to be specified along with values for the associated parameters
- [ ]  input "event_indicator" could be extended to account for competing risks?
- [x] The input of "survivival_time" has a typo, which need correcting
- [x] Change the handling of factor variables; more logical to handle this within pre_processing input, rather than users needing to do this separately
- [x] Create internal function to do the pre_processing steps to remove clutter in the main pm_input_info function - will make this part easier to maintain
- [x] Think about how best to generalise for multiple models as inputs. Either multiple pm_input_info() calls, one for each model, or change the code such that the inputs for this function become lists with an element for each pre-existing model?
- [x] Change the class of the output to depend on model type rather than a generic "pminfo" class. Specifically, have child classes for each kind of model (i.e. survival, logistic) that are then handled as appropriate by pm_predict's UseMethod dispatch (and ultimately similar for pm_validate etc). This will make it easier to add additional methods over time
- [x] Create internal function to do input checks for pm_input_info(), to help readability of main code. Also create internal functions per model type, rather than repeated if statements - will make it easier to add modelling methods later if more modulated 
- [ ] Add handling of "+." in formula such that all variables of newdata are considered in the functional form of the regression model. Need to think how this will interact with pre_processing
