### ISSUE TITLE
Create pm_validate()

### ISSUE THREAD

**Issue by GlenMartin31** [GlenMartin31/predRupdate#4]
# Overview
Create a function that can take, as inputs, a vector of predicted risks and a vector of outcomes, to calculate the predictive performance (calibration, discrimination, overall accuracy) of the model. Do this initially for logistic regression, then extend to performance measures for time-to-event based prediction models. 

## Intended Outcome
Function called pm_validate() that takes predicted risks and observed outcomes (in the validation data) as inputs, and outputs a table with all the performance metrics relevant to the underlying analytical model (e.g. logistic regression or time-to-event).

# Tasks
- [x] Create separate functions for each of calibration (calibration plot, calibration-in-the-large, calibration slope), discrimination (area under ROC curve) and overall accuracy (Brier score, R-squared) - focus initially on logistic regression based prediction models
- [x] Create a wrapper function for each of the separate performance metric functions - it is this wrapper that will be exported in the package
- [x] Set a class for the output of the function, and create print and summary options
- [x] Add calibration plot to validate_probabilities() function, with options for user to specify if the plot is created or not; consider both binned and flexible (spline-based) calibration plot
- [x] Extend the function to time-to-event based prediction models - create a separate wrapper function called pm_validate_survival()
