### ISSUE TITLE
Create pm_update()

### ISSUE THREAD

**Issue by GlenMartin31** [GlenMartin31/predRupdate#6]
# Overview
Create functions to allow one to apply model updating methods to an existing prediction model

## Intended Outcome
This function should take an existing clinical prediction model (could be of class "pminfo" or simply a vector of linear predictors and vector of outcomes in the validation/updating dataset), allow the user to specify the type of update (intercept update, recalibration, individual term revision, new terms, full model refit), and then output the new prediction model.

# Tasks
- [x] Create individual functions that apply different types of model updating 
- [x] Create a wrapper function, that takes two possible methods: either an object of class "pminfo" or a vector of linear predictors and vector of outcomes in the validation/updating dataset (the latter assuming the user has calculated the linear predictor in the validation/update dataset themselves)
- [x] Output the updated prediction model (coefficients, parameter names, and possibly predicted risks from the new model)
- [x] Define the output as class "pminfo" such that print/summary methods for that class apply to the updated model
